# Generated by Django 2.1.9 on 2019-07-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20190702_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='input_image',
            field=models.ImageField(default='', upload_to='static/input_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='style_image',
            field=models.ImageField(default='', upload_to='static/style_images'),
        ),
    ]
